### PR TITLE
modules/build/activation.nix: fix missing /dev/shm on upgrade

### PR DESCRIPTION
**Pull request by t184256**
Fixes: #162

I plan for this to be the last MR going into the release, I haven't find other issues during upgrade testing.

Activation-time quick fix was chosen over login-time quick fix because I can imagine a hot loop around login, but activation is slow in comparison.

### CODE REVIEW

**Comment by Gerschtli** [comment]
I do not really get the source of this problem. How can it be that this directory is only missing sometimes and why can we remove this after 21.11?

I think a test for stateVersion < 21.11 would be better then and only run the fix for these cases?

**Comment by t184256** [comment]
> I do not really get the source of this problem. How can it be that this directory is only missing sometimes

The only place it's created in currently is inside the zipball https://github.com/t184256/nix-on-droid/blob/149e5c886999cacfecdab639878865f833408742/pkgs/bootstrap.nix#L10

If you install clean, you get it from zipball unpacking. If you bootstrap on <21.11 and upgrade, it's never created, thus the warning.

> and why can we remove this after 21.11?

Because anyone ever activating 21.11 will have it.

> I think a test for stateVersion < 21.11 would be better then and only run the fix for these cases?

That didn't occur to me, could you propose a fix? Users are supposed to first activate with old stateVersion and only then bump it, right?

**Comment by Gerschtli** [comment]
Got it.

I think a simple mkIf should do it like:
```nix
activationAfter = mkIf (system.stateVersion <some-less-than-op> "21.11") { mkdirDevShm = "..."; };
```
For the `<some-less-than-op>` you could grep through nixpkgs for the correct name.

**Comment by t184256** [comment]
Ah. OK, I figured it out. Tested to upgrade w/o warning and to remove createDevShm after bumping stateVersion.

**Review by Gerschtli — APPROVED** [review]

**Comment by t184256** [comment]
And here's where I place release-21.11 and push the app update.

Go grab a beverage of your choice and celebrate, @Gerschtli, big thanks for all the [code](https://github.com/t184256/nix-on-droid/graphs/contributors) and reviews you've put into it.

**Comment by Gerschtli** [comment]
Nice, thank you too! Like always a lot of fun. Hope some time we can grab one together :)

**Pull request merged**
