### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Gerschtli**
I tried to update some packages, but I get the following for nixpkgs upgrade, do you have any idea?

```
$> nix build -f ./pkgs --argstr arch aarch64 bootstrapZip --show-trace
error: while evaluating the attribute 'buildCommand' of the derivation 'bootstrap-zip' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildCommand' of the derivation 'bootstrap' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'buildPhase' of the derivation 'nix-directory' at /home/tobias/projects/nix-on-droid/pkgs/nix-directory.nix:28:3:
while evaluating the attribute 'exportReferencesGraph' of the derivation 'closure-info' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/closure-info.nix:14:3:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'proot-termux-unstable-2019-09-05-aarch64-unknown-linux-android' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:197:11:
while evaluating the attribute 'buildDeps' of the derivation 'talloc-static-2.1.14-aarch64-unknown-linux-android' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:197:11:
while evaluating the attribute 'stdenv' of the derivation 'zlib-1.2.11-aarch64-unknown-linux-android' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:197:11:
while evaluating the attribute 'defaultNativeBuildInputs' of the derivation 'stdenv-linux' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/default.nix:84:14:
while evaluating the attribute 'bintools' of the derivation 'aarch64-unknown-linux-android-ndk-gcc-binutils-wrapper-' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating the attribute 'bintools_bin' of the derivation 'aarch64-unknown-linux-android-ndk-gcc-binutils-wrapper-' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating the attribute 'buildCommand' of the derivation 'ndk-gcc-binutils' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'installPhase' of the derivation 'ndk-bundle-18.1.5063045' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/mobile/androidenv/deploy-androidpackage.nix:8:3:
while evaluating 'optionalString' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/strings.nix:180:5, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/mobile/androidenv/ndk-bundle/default.nix:10:23:
while evaluating 'makeSearchPathOutput' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/strings.nix:142:5, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/mobile/androidenv/ndk-bundle/default.nix:4:19:
while evaluating 'makeSearchPath' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/strings.nix:122:5, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/strings.nix:142:11:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/strings.nix:123:32, called from undefined position:
while evaluating the attribute 'buildInputs' of the derivation 'openjdk-8u222-ga' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating the attribute 'buildInputs' of the derivation 'cups-2.3.1' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating the attribute 'preFixup' of the derivation 'libusb-1.0.23' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating 'optionalString' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/strings.nix:180:5, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/libraries/libusb1/default.nix:31:14:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'systemd-243.7' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/stdenv/generic/make-derivation.nix:191:11:
while evaluating the attribute 'passAsFile' of the derivation 'python3-3.7.6-env' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating 'requiredPythonModules' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/top-level/python-packages.nix:64:27, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/interpreters/python/wrapper.nix:15:13:
while evaluating 'unique' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:643:12, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/top-level/python-packages.nix:66:6:
while evaluating 'unique' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:643:12, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:649:17:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:152:16, called from undefined position:
while evaluating the attribute 'outPath' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/customisation.nix:159:7:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'python3.7-lxml-4.4.2' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/interpreters/python/mk-python-derivation.nix:105:3:
while evaluating the attribute 'out.outPath' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/customisation.nix:151:13:
while evaluating the attribute 'buildInputs' of the derivation 'python3.7-Cython-0.29.14' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/interpreters/python/mk-python-derivation.nix:105:3:
while evaluating the attribute 'configureFlags' of the derivation 'aarch64-unknown-linux-android-gdb-8.3.1' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/tools/misc/gdb/default.nix:27:3:
while evaluating the attribute 'stdenv.cc.cc.lib' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/cc-wrapper/default.nix:102:10:
attribute 'lib' missing, at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/development/tools/misc/gdb/default.nix:15:4
```

### CODE REVIEW

**Comment by t184256** [comment]
I'd check whether Hydra can build NDK and try to find the last working version. NDK used to be 'androidenv.androidPkgs_9_0.ndk-bundle', not sure if this changed in 20.03, I haven't tried it yet.

**Comment by Gerschtli** [comment]
androidenv.androidPkgs_9_0.ndk-bundle is still working..

**Comment by Gerschtli** [comment]
Furthermore we should create an workflow to update this regularly

**Comment by Gerschtli** [comment]
PTAL. I've updated some packages and nixpkgs version. Things you need to do: Build `ci.nix` locally and push everything to your cachix. Furthermore it would be nice, if you would build `htop` on your device and push this derivation too.

**Comment by t184256** [comment]
Merged, pushed cross-compiled `proot`, pushed native-compiled `htop` (that was a bit tricky cause cachix wasn't in aarch64 bincache). Thanks for sorting this out.

**Comment by t184256** [comment]
Yeah, and clean install / update both went smoothly.

**Comment by Gerschtli** [comment]
Thank you. The thing I still can't figure out is why this overlay for gdb is needed since release-20.03.. But as long as it works this way, it seems good enough.

**Pull request merged**
