### PR TITLE
release 23.05

### PR DESCRIPTION
**Pull request by t184256**

### CODE REVIEW

**Comment by t184256** [comment]
Thanks for saving me several hours of building time with the re-run.

**Review by Gerschtli — APPROVED** [review]
LGTM, did you test it on a real device?

**Comment by t184256** [comment]
Yes:

1. normal bootstrap
2. flake bootstrap
3. normal bootstrap of 22.11, installing typespeed, upgrading
4. normal bootstrap of 22.11, installing typespeed through h-m, upgrading
5. flake bootstrap of 22.11, upgrading

**Comment by Gerschtli** [comment]
Nice, then let's go :) You can merge and do the release stuff anytime :) Thank you for doing this release!

**Comment by t184256** [comment]
f435d6b21 - autosquashed...

**Comment by t184256** [comment]
Thanks for a quick review!

**Pull request merged**
