### PR TITLE
prerelease-22.05 part 1

### PR DESCRIPTION
**Pull request by t184256**
There are some changes we'd have to do anyway, so I want to get them out of the way before doing the switch to on-device proot building. Untested so far.

### CODE REVIEW

**Comment by Gerschtli** [comment]
LGTM, please also update nixpkgs in github actions.

**Comment by t184256** [comment]
ooh, that's where the old nix came from

**Comment by t184256** [comment]
Not many changes from `prerelease-22.05-pt1-v1` you've reviewed, mainly updating initial nix. Sorry for the force-pushes.

**Comment by Gerschtli** [comment]
No worries, diff LGTM :)

**Pull request merged**
