### PR TITLE
home-manager 20.03 upgrade

### PR DESCRIPTION
**Pull request by Gerschtli**
This PR introduces changes needed for the 20.03 release of home-manager. On 19.09 releases of home-manager this won't work.

Furthermore I added the useGlobalPkgs option recently introduced to home-manager.

### CODE REVIEW

**Comment by t184256** [comment]
Does that mean that it'll stop working with the 19.09 one?

**Comment by Gerschtli** [comment]
Yes, thats right unfortunately.. They updated the requirements for the modules.nix args.

**Comment by t184256** [comment]
Then the minimum is probably to update the home-manager version we setup for the new installs, the reasonable maximum is to block updates with a meaningful message when the home-manager version is too old.

**Comment by Gerschtli** [comment]
Or we could go the way like home-manager and create separate channels for nixos releases.

**Comment by t184256** [comment]
That's a very good idea, and I'm all for it, but it's orthogonal to the problem of upgrading the existing installations.

**Comment by Gerschtli** [comment]
This PR does now contain the https://github.com/t184256/nix-on-droid/pull/60.

So if you create a `release-19.09` and `release-20.03` branch we could advise the users to use the release channels in the future.

**Comment by t184256** [comment]
I've created/pushed a `release-19.09` branch, and I'm going to build/publish the corresponding bootstraps as well. Will create a `release-20.03` on merging this one.

Could you please add something like an assertion for the presence of that new option, with a message instructing to use a newer h-m channel?

**Comment by Gerschtli** [comment]
Something like this? You should consider removing this hack in the near future as it does not allow config merges for the home-manager options..

**Comment by t184256** [comment]
Tried upgrading to 8cc3540 at my testing device, got
`file 'home-manager/modules/modules.nix' was not found in the Nix search path ... modules/home-manager.nix:10:45`.

BTW, any other upgrading ideas aside of adding that assertion?

**Comment by Gerschtli** [comment]
Could you try this one?

**Comment by t184256** [comment]
The assertion fired up OK. Switched the channel, rebuild fails with file `attribute 'submoduleWith' missing, at .../modules/home-manager.nix:15:14`.

**Comment by t184256** [comment]
Changing the nixpkgs to 20.03 made it go away. Is it worth reflecting in the same/separate assertion message?

**Comment by Gerschtli** [comment]
Oh yes, for sure. Just make sure the commits with the assertions are not added in release-20.03.

I can write the assertion tomorrow or you could do it if you like.

**Comment by t184256** [comment]
> Just make sure the commits with the assertions are not added in release-20.03.

Why? And how? They have to be on master.

**Comment by t184256** [comment]
OK, I'd like to leave it to you, I guess.

Just FYI, I went ahead and

1) tested that the clean installation works: it does
2) updated my 'stable' tablet to 20.03: it worked well too

So, all in all, it's working fine, great job! I'd merge it already if not for the second assertion and that comment of yours about not having them on 20.03. It can wait, no rush.

**Comment by Gerschtli** [comment]
I've added the assertion.

For my other comment: I thought about it, but as everyone currently uses master as nix-channel, its alright. When 20.09 is out we should maybe drop the assertions and fully use the release branches for this kind of assertions

**Comment by t184256** [comment]
Re-tested upgrading once again, worked as intended. Thanks a lot for your work!

**Comment by Gerschtli** [comment]
Fun as always :)

**Pull request merged**
