### PR TITLE
nix: add package option

### PR DESCRIPTION
**Pull request by Gerschtli**
Resolves https://github.com/t184256/nix-on-droid/issues/128

### CODE REVIEW

**Comment by t184256** [comment]
Hi, thanks for looking into this.

1) could you bump copyright years on the affected files? might be silly, but still
2) `nix-on-droid` script won't pick the selected version, right? at least I don't see how it would.

**Comment by Gerschtli** [comment]
Will bump the years in a minute.
nix-on-droid should use the defined nix through https://github.com/t184256/nix-on-droid/pull/129/files#diff-dd4183ac01238a8af6cb39b8e12afd4fc614d11cf15167ce7a9c8712d0c337d3R45

**Comment by t184256** [comment]
How could I possibly overlook that, I wonder =o

**Comment by t184256** [comment]
What I'm up to: playing with it by setting it to `nixFlakes` and trying to evict the old nix from the system entirely. Went down to the single referrer being the generation itself (why, how), but now am unwinding and recovering back from `nix-on-droid` not liking `nixFlakes` as its `nix`.

**Comment by Gerschtli** [comment]
So there is still a reference to the default nix package despite changing this option? Can you clarify where the reference is exactly?

**Comment by t184256** [comment]
If only I knew how to check.

Assorted notes so that it's easier for me to retrace:

1) just setting it to `nixFlakes` isn't enough, one also needs at least `experimental-features = nix-command`
2) after rebuilding a generation with `nixFlakes` and re-logging in, it loses the `channels` part of `$NIX_PATH`, rendering `nix-on-droid` unusable until one corrects that as well
3) `nix-store --query --referrers` lists generation and, oddly enough, channels. channels go away after `nix-channel update` with a new nix, hasn't figured out how to understand why derivation refers to old nix (dump it as a nar, maybe?)

**Comment by t184256** [comment]
Found it! It's in `activation` itself, `modules/build/activation.nix:22`.

**Comment by Gerschtli** [comment]
Nice thank you

**Comment by t184256** [comment]
OK, I haven't dug to the bottom of why `$NIX_PATH` is the way it is (and stops being the way it is with `nixFlakes`), but this absolutely doesn't devalue this PR, so, merging. Thank you!

**Review by t184256 — APPROVED** [review]

**Pull request merged**
