### PR TITLE
prerelease-22.05-pt2

### PR DESCRIPTION
**Pull request by t184256**
Use non-prebuilt SDK and attempt to unhardcode a path to proot.

@Gerschtli, if you got time, could you please help me with straightening it out? I know what I want to do here, but not how to do it right. =(

### CODE REVIEW

**Comment by Gerschtli** [comment]
Not sure if I improved it, I don't know how to make this all less strange TBH. It is just that we have 3 different ways how to build proot (bootstrap, on-device, fakedroid), that's why I tried to move this complexity to one file `pkgs/proot-termux/default.nix`.

**Comment by t184256** [comment]
Maybe axing the bootstrap one and going through proot would cut down the complexity? Will have to fix the proot one first though.

**Comment by t184256** [comment]
OK, I guess it's time to admit that I, again, don't have the energy to solve these puzzles in reasonable time. Trimmed the switching to non-precompiled proot, so that we can release at least the SDK change.

**Review by Gerschtli — APPROVED** [review]
Sounds good to me! :)

**Comment by t184256** [comment]
Pushed as release-22.05.

**Pull request closed without merging**
